spring:
  application:
    name: service-order
  cloud:
    nacos:
      #nacos服务端地址及端口
      server-addr: 127.0.0.1:7000
      #登录页面账号和密码
      username: nacos
      password: nacos
server:
  port: 8200