spring:
  application:
    name: service-product
  cloud:
    sentinel:
      transport:
        dashboard: localhost:7003
      #默认懒加载机制,也就是说有第一次的流量访问之后才会,这里显示指定直接连接就显示在控制台
      eager: true
    nacos:
      server-addr: 127.0.0.1:7000
      username: nacos
      password: nacos
      #虽然已经引入了nacos-config的依赖，但是暂时不用配置中心配置
      config:
        import-check:
          enabled: false
server:
  port: 8201
